version: '3'
services:
  app:
    container_name: full_app
    build: .
    ports: 
      - 8081:8081 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on: 
      - db           # Uncomment this when using mysql.
    networks:
      - fullstack

  db:
    image: mysql:latest
    ports: 
        - 3305:3306
    environment: 
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    container_name: my_go_app_db
    command: 
      - --default-authentication-plugin=mysql_native_password
    healthcheck: 
      test: ["CMD_SHELL" , "echo 'select 1' |mysql -uroot -pdbrootpass --silent"] 
      interval: 30s 
      timeout: 20s 
      retries: 6     
    networks:
      - fullstack
    volumes:
        - database_mysql:/var/lib/mysql    
        
  

volumes:
  api: 
  database_mysql:          

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge

